title = "D2 SDK"
gitRepoUrl = "https://github.com/karta-creative/d2-sdk"

gitSourceBranch = "main"
changelog = false

[docusaurus]
organizationName = "karta-creative"
projectName = "d2-sdk"
url = "https://webserver-blue-log-4719.fly.dev"
baseUrl = "/d2-sdk"
tagline = "Active life, awesome loot."

[footer]
copyright = "Copyright © 2024 Karta Creative Ltd. Built with Moonwave and Docusaurus"

[home]
enabled = true